accio:
  development: true
  site-username: notauser@notactualdomain.com
  site-password: T76y66wdNpkMSVJpsCRU!*9237!@
  secret: 4OIqGCggyVqapZkULl+x58uKS+eSktyiVc3I8dZeAr4=
  activation-secret: 6PWt5Hj6cXQ/3E/m3p/XkYqzriFOJWvDFW87IcMjqfI=

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accio
    username: dev
    password: GbWXna2tBBGfjqaK
    driver-class-name: org.postgresql.Driver
    hikari:
      leak-detection-threshold: 18000000
    codec:
      max-in-memory-size: 104857600000
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
      enabled: true
      file-size-threshold: 1KB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  web:
    resources:
      add-mappings: true
  banner:
    location: banner.txt
server:
  forward-headers-strategy: framework